
matrix:
  include:
    - language: cpp
      compiler: gcc
      addons:
        apt:
          packages:
            cmake
      script:
        - mkdir build
        - cd build
        - cmake ..
        - make
        - make test
        - make examples
    - language: cpp
      compiler: clang
      addons:
        apt:
          packages:
            cmake
      script:
        - mkdir build
        - cd build
        - cmake ..
        - make
        - make test
        - make examples
    - language: python
      python: 3.4
      install:
        - python setup.py install
      script:
        - python setup.py test
        - cd examples
        - ./exercisers.py
    - language: python
      python: 3.5
      install:
        - python setup.py install
      script:
        - python setup.py test
        - cd examples
        - ./exercisers.py
    - language: python
      python: 3.5-dev
      install:
        - python setup.py install
      script:
        - python setup.py test
        - cd examples
        - ./exercisers.py
    - language: python
      python: 3.6
      install:
        - python setup.py install
      script:
        - python setup.py test
        - cd examples
        - ./exercisers.py
    - language: python
      python: 3.6-dev
      install:
        - python setup.py install
      script:
        - python setup.py test
        - cd examples
        - ./exercisers.py
    - language: python
      python: 3.7
      install:
        - python setup.py install
      script:
        - python setup.py test
        - cd examples
        - ./exercisers.py
    - language: python
      python: 3.7-dev
      install:
        - python setup.py install
      script:
        - python setup.py test
        - cd examples
        - ./exercisers.py
    - language: python
      python: 3.8
      install:
        - python setup.py install
      script:
        - python setup.py test
        - cd examples
        - ./exercisers.py
    - language: python
      python: 3.8-dev
      install:
        - python setup.py install
      script:
        - python setup.py test
        - cd examples
        - ./exercisers.py
    - language: python
      python: 3.9-dev
      install:
        - python setup.py install
      script:
        - python setup.py test
        - cd examples
        - ./exercisers.py
